### ISSUE TITLE
Need to accept any kind of file

### ISSUE THREAD

**Issue by naveenkumargc** [mother/react-files#27]
I would like to know what should we pass in the accepts prop to accept all file types. if we pass '*.*' it is not showing mp4 files in onFilesChange() event. tried '.*' also but no luck.

**Comment by SoulKa** [comment]
just leave the "accepts" prop emtpy, that did work for me

**Comment by asabhaney** [comment]
Fixed via 2da3184b003b966c808cc893ade6ae71ed29001c (published in `3.0.0-alpha.3`)
