### ISSUE TITLE
fileAdded handler, possibility to add/replace/remove files

### ISSUE THREAD

**Issue by Fuzzyma** [mother/react-files#3]
To make this useable in more cases I suggest adding a handler which is called, when files are added to the dropzone. Also it would be cool, to have an api to add files / remove files from the dropzone programatically.

Keep up the good work!

**Comment by jaredreich** [comment]
Not sure if adding files makes sense since the react-files dropzone should be the source of files coming in.

Removing can be done with the parent component like:
```js
filesRemoveOne: function (file) {
    this.refs.files.removeFile(file)
  },

  filesRemoveAll: function () {
    this.refs.files.removeFiles()
  },
```

Documentation needs to be added though.

Thanks for this suggestion.

**Comment by Fuzzyma** [comment]
There is always the possibility, that teh developer wants to alter the files which are dragged into the dropzone. In my case I want to clip the image the user dragged into the browser window. When I am done I would like to proceed as normal, say: adding the new file back to the dropzone. This is needed because this script also manages upload of the files.

**Comment by jaredreich** [comment]
That's a great use case example, thanks for explaining.

Feel free to PR if you've already implemented on your end 😄

**Comment by Fuzzyma** [comment]
I used https://github.com/felixrieseberg/React-Dropzone-Component before which can handle this sort of things. However I was searching for a more lightweight solution and found yours. So unfortunately I did not have any implementation done - sorry

**Comment by jaredreich** [comment]
This is partially satisfied in https://github.com/mother/react-files/pull/4/files with access to files added through `onFilesChange`. Also, overall your use case should be able to be handled by abstracting the dropzone out of your file management. You can use the dropzone as merely the interface to get the files into the browser, but then then adding and removing can take place by your own files array implementation. Please comment or re-file an issue if I am off the mark. Thanks!
