### ISSUE TITLE
Warning: defaultProps deprecatated by React (see: https://github.com/facebook/react/pull/16210)

### ISSUE THREAD

**Issue by femi-Zedev** [mother/react-files#49]
I got this Warning:  Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
I want to fork the project, make the needed changes and create a pull request. 
@asabhaney I would be happy if you take a look at it

**Comment by marcosrjjunior** [comment]
just pushed a quick update to get rid of that annoying warning...

**Comment by asabhaney** [comment]
Closed via #52. Thanks @marcosrjjunior.
