### ISSUE TITLE
Mutiple quickly click `Upload area`

### ISSUE THREAD

**Issue by ZhaoFeiK** [mother/react-files#5]
Hi, do you know how to avoid mutiple quickly click `Upload area` that will call mutiple `select alert`?

**Comment by jaredreich** [comment]
Hi there! Unfortunately I'm unable to reproduce the case of quickly clicking the upload area, causing multiple select alerts. I'm going to close this issue for now, but please re-file and add more detail with reproducible steps if you're still having trouble. Thanks!

**Comment by ZhaoFeiK** [comment]
First the computer is so slow! When click upload area, the file alert window display delay, and the upload area is also enable to click!
