### ISSUE TITLE
use `prop-types` lib instead of React.PropTypes

### ISSUE THREAD

**Issue by darthrellimnad** [mother/react-files#8]
this is a great little lib, thanks for putting this together!! :D

I'm getting a deprecation warning when using `react-files`, since`React.PropTypes` is being deprecated for React v16.  Any plans to update this and use the `prop-types` lib instead?

**Comment by asabhaney** [comment]
Thanks @darthrellimnad! Fixed via https://github.com/mother/react-files/pull/9. Just published to npm as well.
